apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: javajava-ttttttttttesting-multiple-components-long-name-vl2t
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: javajava-ttttttttttesting-multiple-components-long-name-vl2t
    app.kubernetes.io/part-of: my-app-testing2
  name: javajava-ttttttttttesting-multiple-components-long-name-vl2t
  namespace: rsoaresd-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-springboot-app
      app.kubernetes.io/instance: javajava-ttttttttttesting-multiple-components-long-name-vl2t
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-springboot-app
        app.kubernetes.io/instance: javajava-ttttttttttesting-multiple-components-long-name-vl2t
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:8J8em-javajava-ttttttttttesting-multiple-components-long-name-vl2t
        name: my-java-springboot
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 10m
            memory: 180Mi
status: {}
