apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: javajava-ttttttttttesting-multiple-components-long-name-vl2t
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: javajava-ttttttttttesting-multiple-components-long-name-vl2t
    app.kubernetes.io/part-of: my-app-testing2
  name: javajava-ttttttttttesting-multiple-components-long-name-vl2t
  namespace: rsoaresd-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: javajava-ttttttttttesting-multiple-components-long-name-vl2t
    weight: null
status: {}
