apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: javajava-ttttttttttesting-multiple-components-long-name-vl2t
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: javajava-ttttttttttesting-multiple-components-long-name-vl2t
    app.kubernetes.io/part-of: my-app-testing2
  name: javajava-ttttttttttesting-multiple-components-long-name-vl2t
  namespace: rsoaresd-tenant
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: java-springboot-app
    app.kubernetes.io/instance: javajava-ttttttttttesting-multiple-components-long-name-vl2t
status:
  loadBalancer: {}
